/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#a6f4b5",
        "on-tertiary-fixed-variant": "#7f2a21",
        "surface-variant": "#dce5d9",
        "tertiary-fixed": "#ffdad5",
        "on-primary-fixed": "#002109",
        "on-tertiary-fixed": "#410001",
        "on-tertiary": "#ffffff",
        "outline": "#6d7b6c",
        "surface-container-highest": "#dce5d9",
        "error": "#ba1a1a",
        "secondary-container": "#a4f1b2",
        "surface-container": "#e8f0e4",
        "primary": "#006e2f",
        "outline-variant": "#bccbb9",
        "on-background": "#161d16",
        "surface-container-high": "#e2ebde",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#4ae176",
        "inverse-surface": "#2a322a",
        "on-error": "#ffffff",
        "surface-dim": "#d4ddd0",
        "inverse-primary": "#4ae176",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#ebf3e7",
        "background": "#f3fcef",
        "surface": "#f3fcef",
        "on-tertiary-container": "#76231b",
        "surface-bright": "#f3fcef",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#005226",
        "on-secondary": "#ffffff",
        "on-surface": "#161d16",
        "tertiary-fixed-dim": "#ffb4a9",
        "primary-fixed": "#6bff8f",
        "on-primary-container": "#004b1e",
        "on-secondary-fixed": "#00210b",
        "on-secondary-container": "#24703e",
        "tertiary-container": "#ff8b7c",
        "surface-tint": "#006e2f",
        "on-primary-fixed-variant": "#005321",
        "error-container": "#ffdad6",
        "primary-container": "#22c55e",
        "secondary-fixed-dim": "#8bd79b",
        "tertiary": "#9e4036",
        "surface-container-low": "#edf6ea",
        "secondary": "#1f6c3a",
        "on-surface-variant": "#3d4a3d",
      },

      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },

      spacing: {
        gutter: "24px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "container-padding": "32px",
        unit: "8px",
      },

      fontFamily: {
        sans: ["Manrope", "sans-serif"],
      },

      fontSize: {
        "label-sm": ["14px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6" }],
        "body-lg": ["18px", { lineHeight: "1.6" }],
        "h1": ["40px", { lineHeight: "1.2", fontWeight: "700" }],
        "h2": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "h3": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "caption": ["12px", { lineHeight: "1.4" }],
      },
    },
  },
  plugins: [],
};
